# From Pure preset ( https://starship.rs/presets/pure-preset.html < https://github.com/sindresorhus/pure)
# I think I removed dependencies on NerdFonts. (Meslo)
format = """
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character"""

# can be inserted into the format before $character
# $line_break\

[username]
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
# ssh_symbol = "ğŸŒ "  #  ğŸŒ ğŸŒ ğŸŒ
ssh_symbol = ""  # remove altogether
# style = "bold dimmed green" - default
style = "green"
format = "@[$ssh_symbol$hostname]($style)"

[directory]
truncation_length = 2
truncation_symbol = ".../"
truncate_to_repo = false
format = ":[$path]($style)[$read_only]($read_only_style) "
style = "blue"


[git_branch]
#format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol = ""  # default "î‚  "
format = "$symbol$branch($style)"
style = "bright-black"

[git_status]
# TODO(daneroo): perhaps color to help the meaning
# e.g. modified = "MOD[$count](red)"
ahead = ">"  # default "â‡¡"
behind = "<" # default "â‡£"

[git_state]
# default format
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
show_milliseconds = true
format = "[$duration]($style) "
style = "yellow"

[character]
# default symbols
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"
# success_symbol = '[âœ](bold green)'
# error_symbol = '[âœ—](bold red)'
# success_symbol = '[\$](green)'
# error_symbol = '[\$](red)'


[kubernetes]
disabled = false
#detect_files = ['k8s']
#detect_folders = ['k8s']
#detect_extensions = ['yaml']