# From Pure preset
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$character"""

# $line_break\

[username]
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
ssh_symbol = "ğŸŒ "  # remove trailing space : ğŸŒ ğŸŒ ğŸŒ
# style = "bold dimmed green" - default
style = "green"
format = "@[$ssh_symbol$hostname]($style)"

[directory]
truncation_length = 2
truncation_symbol = ".../"
truncate_to_repo = false
format = ":[$path]($style)[$read_only]($read_only_style) "
style = "blue"


[git_branch]
#format = "on [$symbol$branch(:$remote_branch)]($style) "
format = "$symbol$branch($style)"
style = "bright-black"

[git_status]
ahead = ">"  # default "â‡¡"
behind = "<" # default "â‡£"
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[character]
# success_symbol = "[â¯](green)"
# error_symbol = "[â¯](red)"
